import 'dart:developer';

import 'package:dio/dio.dart';
import 'package:practice/model/postmodel.dart';
import 'package:practice/service/services.dart';

class PostController {
  List<Autogenerated> postlist = [];
//initialize network service
  late HttpServices _httpServices;

  PostController() {
    //instance of network service
    _httpServices = HttpServices();
  }

  // request from frontend using endpoint

  Future<List<Autogenerated>> getPost() async {
    Response response;
    try {
      response = await _httpServices.getRequest('/posts');
      if (response.statusCode == 200) {
        List<dynamic> responseData = response.data;
        responseData.forEach((single_response) {
          postlist.add(Autogenerated.fromJson(single_response));
        });
      }
    } catch (e) {
      log(e.toString());
    }
    return postlist;
  }

  Future<void> createPost(Autogenerated newPost) async {
    try {
      //make post request to create new post
      Response response =
          await _httpServices.postRequest("/posts", data: newPost.toJson());
      if (response.statusCode == 201) {
        log('New post is created ${response.data}');
      } else {
        log('Failed to create post ${response.statusCode}');
      }
    } catch (e) {
      log('error while creating post : $e');
    }
  }
}
