import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:practice/controller/postcontroller.dart';

import 'package:practice/model/postmodel.dart';
import 'package:practice/view/addpost.dart';
import 'package:practice/view/postdetails.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Autogenerated>? posts;
  //intialize
  late PostController _postController;

  void getPost() async {
    posts = await _postController.getPost();
    setState(() {});
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _postController = PostController();
    getPost();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(actions: [
          IconButton(
            onPressed: () {
              Navigator.push(
                  context, MaterialPageRoute(builder: (context) => Addpost()));
            },
            icon: const Icon(Icons.add),
          )
        ]),
        body: ListView.builder(
          itemCount: posts?.length ?? 0,
          itemBuilder: (context, index) {
            return GestureDetector(
              onTap: () {
                log('hello');
                Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) =>
                            Postdetails(posts: posts![index])));
              },
              child: Card(
                elevation: 1,
                color: Colors.blueAccent,
                child: ListTile(
                  title: Text(posts![index].title.toString()),
                  // subtitle: Text(posts![index].body.toString()),
                ),
              ),
            );
          },
        ));
  }
}
